// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/wry_webview/window.dart';
import 'api/wry_webview/wry_webview_config.dart';
import 'api/wry_webview/wry_webview_controller.dart';
import 'api/wry_webview/wry_webview_error.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    await api.crateApiSimpleInitApp();

                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.11.1';

                  @override
                  int get rustContentHash => -290586101;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'flutter_wry',
                    ioDirectory: 'rust/target/release/',
                    webPrefix: 'pkg/',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<WryWebViewController> crateApiWryWebviewWryWebviewControllerWryWebViewControllerNew({required WryWebViewConfig config , required FlutterWindowHandle handle });

Future<FlutterWindow> crateApiWryWebviewWindowFlutterWindowNew({required FlutterWindowHandle window });

String crateApiSimpleGreet({required String name });

Future<void> crateApiSimpleInitApp();

Future<WryWebViewConfig> crateApiWryWebviewWryWebviewConfigWryWebViewConfigDefault();

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_WryWebViewController;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_WryWebViewController;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WryWebViewControllerPtr;


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<WryWebViewController> crateApiWryWebviewWryWebviewControllerWryWebViewControllerNew({required WryWebViewConfig config , required FlutterWindowHandle handle })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_wry_web_view_config(config, serializer);
sse_encode_box_autoadd_flutter_window_handle(handle, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWryWebViewController,
          decodeErrorData: sse_decode_wry_web_view_error,
        )
        ,
            constMeta: kCrateApiWryWebviewWryWebviewControllerWryWebViewControllerNewConstMeta,
            argValues: [config, handle],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiWryWebviewWryWebviewControllerWryWebViewControllerNewConstMeta => const TaskConstMeta(
            debugName: "WryWebViewController_new",
            argNames: ["config", "handle"],
        );
        

@override Future<FlutterWindow> crateApiWryWebviewWindowFlutterWindowNew({required FlutterWindowHandle window })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_flutter_window_handle(window, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_flutter_window,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiWryWebviewWindowFlutterWindowNewConstMeta,
            argValues: [window],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiWryWebviewWindowFlutterWindowNewConstMeta => const TaskConstMeta(
            debugName: "flutter_window_new",
            argNames: ["window"],
        );
        

@override String crateApiSimpleGreet({required String name })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(name, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiSimpleGreetConstMeta,
            argValues: [name],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
            debugName: "greet",
            argNames: ["name"],
        );
        

@override Future<void> crateApiSimpleInitApp()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiSimpleInitAppConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
            debugName: "init_app",
            argNames: [],
        );
        

@override Future<WryWebViewConfig> crateApiWryWebviewWryWebviewConfigWryWebViewConfigDefault()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_wry_web_view_config,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiWryWebviewWryWebviewConfigWryWebViewConfigDefaultConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiWryWebviewWryWebviewConfigWryWebViewConfigDefaultConstMeta => const TaskConstMeta(
            debugName: "wry_web_view_config_default",
            argNames: [],
        );
        

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_WryWebViewController => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWryWebViewController;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_WryWebViewController => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWryWebViewController;



                  @protected WryWebViewController dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWryWebViewController(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return WryWebViewControllerImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected WryWebViewController dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWryWebViewController(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return WryWebViewControllerImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected bool dco_decode_box_autoadd_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected FlutterWindowHandle dco_decode_box_autoadd_flutter_window_handle(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_flutter_window_handle(raw); }

@protected WryWebViewConfig dco_decode_box_autoadd_wry_web_view_config(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_wry_web_view_config(raw); }

@protected FlutterWindow dco_decode_flutter_window(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 1) throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
                return FlutterWindow(window: dco_decode_flutter_window_handle(arr[0]),); }

@protected FlutterWindowHandle dco_decode_flutter_window_handle(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return FlutterWindowHandle_Hwnd(dco_decode_isize(raw[1]),);
                default: throw Exception("unreachable");
            } }

@protected PlatformInt64 dco_decode_isize(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeI64(raw); }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected String? dco_decode_opt_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_String(raw); }

@protected bool? dco_decode_opt_box_autoadd_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_box_autoadd_bool(raw); }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected BigInt dco_decode_usize(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected WryWebViewConfig dco_decode_wry_web_view_config(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return WryWebViewConfig(initialUrl: dco_decode_opt_String(arr[0]),
initialHtml: dco_decode_opt_String(arr[1]),
initialFocused: dco_decode_opt_box_autoadd_bool(arr[2]),
initialDevtools: dco_decode_opt_box_autoadd_bool(arr[3]),); }

@protected WryWebViewError dco_decode_wry_web_view_error(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return WryWebViewError_CreationError(dco_decode_String(raw[1]),);
case 1: return WryWebViewError_UnsupportedPlatform();
                default: throw Exception("unreachable");
            } }

@protected WryWebViewController sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWryWebViewController(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return WryWebViewControllerImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected WryWebViewController sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWryWebViewController(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return WryWebViewControllerImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected bool sse_decode_box_autoadd_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_bool(deserializer)); }

@protected FlutterWindowHandle sse_decode_box_autoadd_flutter_window_handle(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_flutter_window_handle(deserializer)); }

@protected WryWebViewConfig sse_decode_box_autoadd_wry_web_view_config(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_wry_web_view_config(deserializer)); }

@protected FlutterWindow sse_decode_flutter_window(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_window = sse_decode_flutter_window_handle(deserializer);
return FlutterWindow(window: var_window); }

@protected FlutterWindowHandle sse_decode_flutter_window_handle(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: var var_field0 = sse_decode_isize(deserializer);
return FlutterWindowHandle_Hwnd(var_field0); default: throw UnimplementedError(''); }
             }

@protected PlatformInt64 sse_decode_isize(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getPlatformInt64(); }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected String? sse_decode_opt_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_String(deserializer));
            } else {
                return null;
            }
             }

@protected bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_box_autoadd_bool(deserializer));
            } else {
                return null;
            }
             }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected BigInt sse_decode_usize(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected WryWebViewConfig sse_decode_wry_web_view_config(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_initialUrl = sse_decode_opt_String(deserializer);
var var_initialHtml = sse_decode_opt_String(deserializer);
var var_initialFocused = sse_decode_opt_box_autoadd_bool(deserializer);
var var_initialDevtools = sse_decode_opt_box_autoadd_bool(deserializer);
return WryWebViewConfig(initialUrl: var_initialUrl, initialHtml: var_initialHtml, initialFocused: var_initialFocused, initialDevtools: var_initialDevtools); }

@protected WryWebViewError sse_decode_wry_web_view_error(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: var var_field0 = sse_decode_String(deserializer);
return WryWebViewError_CreationError(var_field0);case 1: return WryWebViewError_UnsupportedPlatform(); default: throw UnimplementedError(''); }
             }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWryWebViewController(WryWebViewController self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as WryWebViewControllerImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWryWebViewController(WryWebViewController self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as WryWebViewControllerImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_bool(self, serializer); }

@protected void sse_encode_box_autoadd_flutter_window_handle(FlutterWindowHandle self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_flutter_window_handle(self, serializer); }

@protected void sse_encode_box_autoadd_wry_web_view_config(WryWebViewConfig self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_wry_web_view_config(self, serializer); }

@protected void sse_encode_flutter_window(FlutterWindow self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_flutter_window_handle(self.window, serializer);
 }

@protected void sse_encode_flutter_window_handle(FlutterWindowHandle self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case FlutterWindowHandle_Hwnd(field0: final field0): sse_encode_i_32(0, serializer); sse_encode_isize(field0, serializer);
  } }

@protected void sse_encode_isize(PlatformInt64 self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putPlatformInt64(self); }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_opt_String(String? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_String(self, serializer);
                }
                 }

@protected void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_box_autoadd_bool(self, serializer);
                }
                 }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_usize(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }

@protected void sse_encode_wry_web_view_config(WryWebViewConfig self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_opt_String(self.initialUrl, serializer);
sse_encode_opt_String(self.initialHtml, serializer);
sse_encode_opt_box_autoadd_bool(self.initialFocused, serializer);
sse_encode_opt_box_autoadd_bool(self.initialDevtools, serializer);
 }

@protected void sse_encode_wry_web_view_error(WryWebViewError self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case WryWebViewError_CreationError(field0: final field0): sse_encode_i_32(0, serializer); sse_encode_String(field0, serializer);
case WryWebViewError_UnsupportedPlatform(): sse_encode_i_32(1, serializer);   } }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }
                }
                

            @sealed class WryWebViewControllerImpl extends RustOpaque implements WryWebViewController {
                // Not to be used by end users
                WryWebViewControllerImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                WryWebViewControllerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_WryWebViewController,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_WryWebViewController,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_WryWebViewControllerPtr,
                );

                
            }