// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class WryWebViewConfig {
  /// Load the provided URL when the builder calling [`WebViewBuilder::build`] to create the [`WebView`].
  /// The provided URL must be valid.
  ///
  /// ## Note
  ///
  /// Data URLs are not supported, use [`html`](Self::with_html) option instead.
  final String? url;

  /// Load the provided HTML string when the builder calling [`WebViewBuilder::build`] to create the [`WebView`].
  /// This will be ignored if `url` is provided.
  ///
  /// # Warning
  ///
  /// The Page loaded from html string will have `null` origin.
  ///
  /// ## PLatform-specific:
  ///
  /// - **Windows:** the string can not be larger than 2 MB (2 * 1024 * 1024 bytes) in total size
  final String? html;

  /// Set whether the webview should be focused when created.
  ///
  /// ## Platform-specific:
  ///
  /// - **macOS / Android / iOS:** Unsupported.
  final bool? focused;

  /// Enable or disable web inspector which is usually called devtools.
  ///
  /// Note this only enables devtools to the webview. To open it, you can call
  /// [`WebView::open_devtools`], or right click the page and open it from the context menu.
  ///
  /// ## Platform-specific
  ///
  /// - macOS: This will call private functions on **macOS**. It is enabled in **debug** builds,
  ///   but requires `devtools` feature flag to actually enable it in **release** builds.
  /// - Android: Open `chrome://inspect/#devices` in Chrome to get the devtools window. Wry's `WebView` devtools API isn't supported on Android.
  /// - iOS: Open Safari > Develop > [Your Device Name] > [Your WebView] to get the devtools window.
  final bool? devtools;

  /// Defaults to `x: 0, y: 0`.
  final WryWebViewPosition? position;

  /// Defaults to `width: 800, height: 600`.
  final WryWebViewSize? size;

  const WryWebViewConfig({
    this.url,
    this.html,
    this.focused,
    this.devtools,
    this.position,
    this.size,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      html.hashCode ^
      focused.hashCode ^
      devtools.hashCode ^
      position.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WryWebViewConfig &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          html == other.html &&
          focused == other.focused &&
          devtools == other.devtools &&
          position == other.position &&
          size == other.size;
}

class WryWebViewPosition {
  final double x;
  final double y;

  const WryWebViewPosition({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WryWebViewPosition &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

class WryWebViewSize {
  final double width;
  final double height;

  const WryWebViewSize({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WryWebViewSize &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}
