// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'wry_webview_error.freezed.dart';

@freezed
sealed class WryWebViewError with _$WryWebViewError implements FrbException {
  const WryWebViewError._();

  const factory WryWebViewError.creationError(String field0) =
      WryWebViewError_CreationError;
  const factory WryWebViewError.unsupportedPlatform() =
      WryWebViewError_UnsupportedPlatform;
}
