// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'window.freezed.dart';

            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `window_handle`


            

            class FlutterWindow  {
                final FlutterWindowHandle window;

                const FlutterWindow({required this.window ,});

                  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
static Future<FlutterWindow>  newInstance({required FlutterWindowHandle window })=>RustLib.instance.api.crateApiWryWebviewWindowFlutterWindowNew(window: window);


                

                
        @override
        int get hashCode => window.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is FlutterWindow &&
                runtimeType == other.runtimeType
                && window == other.window;
        
            }

@freezed
                sealed class FlutterWindowHandle with _$FlutterWindowHandle  {
                    const FlutterWindowHandle._();

                     const factory FlutterWindowHandle.hwnd(  PlatformInt64 field0,) = FlutterWindowHandle_Hwnd;

                    

                    
                }
            