// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'window.dart';
import 'wry_webview_config.dart';
import 'wry_webview_error.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WryWebViewController>>
abstract class WryWebViewController implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WryWebViewController> newInstance({
    required WryWebViewConfig config,
    required FlutterWindowHandle handle,
  }) => RustLib.instance.api
      .crateApiWryWebviewWryWebviewControllerWryWebViewControllerNew(
        config: config,
        handle: handle,
      );
}
